# Generated by Django 5.0.6 on 2024-07-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id']},
        ),
    ]
